language: android
jdk: oraclejdk8
sudo: required # false for Container-Based Infrastructure, required for Sudo-Enabled Infrastructure
#group: deprecated-2017Q4

before_cache:
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/modules-2/modules-2.lock # Avoid to repack it due locks
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/classAnalysis/classAnalysis.lock
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/jarSnapshots/jarSnapshots.lock

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - TARGET_SDK=27
    - BUILD_TOOLS_VERSION=27.0.2
  matrix:
    - EMULATOR_SDK=android-22 ABI=armeabi-v7a

android:
  components: # Cookbooks version: https://github.com/travis-ci/travis-cookbooks/tree/9c6cd11
    - tools
    - platform-tools
    - tools
    - android-${TARGET_SDK}
    - android-26
    - android-22
    - build-tools-${BUILD_TOOLS_VERSION}
    - extra-android-m2repository


before_install:
#  - export EMULATOR="system-images;android-${API};${TAG};${ABI}" # Used to install/create emulator
#  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid warning
  - openssl aes-256-cbc -K $encrypted_923bf72da533_key -iv $encrypted_923bf72da533_iv -in ci/secrets.tar.enc -out ci/secrets.tar -d
  - tar xvf ci/secrets.tar
  - chmod +x gradlew


before_script:
  - android-update-sdk --components=sys-img-$ABI-$EMULATOR_SDK --accept-licenses='android-sdk-license-[0-9a-f]{8}'
  - mkdir -p $ANDROID_HOME/licenses
  - ls $ANDROID_HOME || true
  - ls $ANDROID_HOME/licences || true
  - touch $ANDROID_HOME/licenses/android-sdk-license
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
  #- yes | sdkmanager --licenses
  - echo no | android create avd --force -n test -t $EMULATOR_SDK --abi $ABI
  - emulator -avd test -no-audio -no-window &
  - ./gradlew clean build
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew jacocoTestReport
  - travis_wait 60 ./gradlew connectedCheck

after_script:
  # Show tests and lint results
  #- cat ${TRAVIS_BUILD_DIR}/*/build/outputs/androidTest-results/connected/*
  #- cat ${TRAVIS_BUILD_DIR}/*/build/reports/lint-results.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)